services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: devdb
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: devdb@dev.db
      PGADMIN_DEFAULT_PASSWORD: 123
      PGADMIN_LISTEN_PORT: 80 # Porta di ascolto interna di pgAdmin
      PGADMIN_CONFIG_SERVER_MODE: "True"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: "10"
      PGADMIN_SERVER_JSON_FILE: "/pgadmin4/servers.json"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json # Server configurato all'avvio
    ports:
      - "8088:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:
